version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: micraft_postgres
    environment:
      POSTGRES_USER: micraft
      POSTGRES_PASSWORD: micraft_pass
      POSTGRES_DB: micraft_leads
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: micraft_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
